### ISSUE TITLE
Need help with this weeks assignment

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/content-semantics#1]
@hellachella

**Comment by hellachella** [comment]
Please upload screenshots etc/describe the issue.

**Comment by Jessica-Lee123** [comment]
<img width="1870" alt="Stuck here" src="https://user-images.githubusercontent.com/77642609/107830788-963d0e00-6d5a-11eb-9d35-e69b3db4e405.png">

**Comment by Jessica-Lee123** [comment]
<img width="1589" alt="Screen Shot 2021-02-12 at 2 10 06 PM" src="https://user-images.githubusercontent.com/77642609/107830807-a359fd00-6d5a-11eb-966a-8ccf3b0fe2e2.png">

**Comment by Jessica-Lee123** [comment]
Sorry, I sent the other issue here first. Please see second image for this issue.

**Comment by hellachella** [comment]
Your `<aside>` is inside of the `<ul>`, which is the problem.  Close the `<aside>` after it.

**Comment by Jessica-Lee123** [comment]
<img width="2560" alt="Screen Shot 2021-02-18 at 1 00 29 P@hellachella src="https://user-images.githubusercontent.com/77642609/108400566-5908ce00-71e9-11eb-956c-cbe3be7504a3.png">

@hellachella 

I tried making these changes as well, no luck, but not as bad as the masthead assignment! ;) LOL!
 I just don't get it though, I can't see my own mistakes. So hard being home and not in-person to just quickly get answers.  
I finally get paid next week from a 6-month long freelance job, I'll try to hire myself a web tutor then, the 5pm TA meetings don't work with my "mom-schedule". :( Thank you for trying to help, I know you have a ton of other students to work with though, so I don't want to keep bothering you every week.

**Comment by hellachella** [comment]
You don't bother me. We can do another zoom session.
